<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQNWoo5R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQNWoo5R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQNWoo5R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQNWoo5R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQNWoo5R\App_KernelDevDebugContainer([
    'container.build_hash' => 'QNWoo5R',
    'container.build_id' => '0c0b2059',
    'container.build_time' => 1747038803,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQNWoo5R');
